### ISSUE TITLE
database import from antennapod

### ISSUE THREAD

**Issue by stoponerr** [allentown521/FocusPodcast#1]
feature request

latest fdroid antennapod (3.4.0f) database is incompatible, reports as too new of a version.

**Comment by engelhro** [comment]
I'm affected by the same problem. As FocusPodcast is (like Podcini, which I dislike for certain reasons) a fork of AntennaPod, keeping database compatibility should be a priority, allowing an easy switch.

It's not only about the statistics, as the reply above suggests – the database contains _everything_ useful you don't want to lose: listened/unlistened status for all episodes, download status for all episodes (even if the actual downloads have to be repeated as the target location changes with another app), the queue (playlist) and progress, the various filters for the abonnements, the history, various settings (GUI, play behaviour, download options, notifications, etc.) and more.

**That's** what you don't want to loose during a migration, and it's the reason the database is several megabytes big.

The tiny OPML file is rather useless here. Yes, it contains a list of the sources (subscribed podcasts), but that's it. Importing it helps only to restore the subscriptions themselves, but **everything else** is lost. We need the actual _database_ imported instead and then its contents restored where applicable.

**Comment by stoponerr** [comment]
the reply above suggests its about statistics because thats all i care about keeping. i got my settings right in less than 10 minutes, and i can easily see the differences between settings in each app being what makes this difficult to implement.

**Comment by engelhro** [comment]
Yeah, that might apply to **you** but not to me (and probably others). For example:

- For each of many subscribed podcasts I have a list of episodes not heard so far - to lose that information (= manually maintaining it after migration) would be unacceptable for me.
- Also setting up the current playlist again would be a pain in the ass (although doable of course, but very tedious).
- The same applies to the favorites.
- And also the list of downloaded episodes (does not necessarily match the playlist, does not necessarily match the list of unheard episodes, does not necessarily match the list of favorites) is long and cannot be easily reconstructed.

So everyone has different requirements which could most easily be fulfilled by a working import feature in the first place :smiley:

Yes, the settings are slightly different as both apps (or, including Podcini, all three apps) are similar but not the same – they'll develop in different directions over time (I guess). That's why I wrote "restore contents where applicable" above: _identical_ settings should be taken over on import/migration while this cannot happen of course for any _unique_ setting on either side.

Let's see what @allentown521 thinks of this request.

**Comment by allentown521** [comment]
@engelhro That's right. I can relax the database version restriction when importing. The database will be imported successfully, but the app will crash when running because the database versions of FocusPodcast and Antennapod are different, and even the table fields are inconsistent, and the playback time and some data are lost. Unfortunately, migration also costs a lot, which is very regrettable, but when we treat them as completely independent apps, we don’t just have to choose 1 from 2.
